[package]
name = "algorithm"
version = "0.1.0"
authors = ["AprilNEA <github@sku.moe>"]
edition = "2021"
autobins = true

[[bin]]
name = "algorithm"  # 这是生成的可执行文件的名称
path = "main.rs"

[dependencies]
rand = "0.3.14"